spring.application.name=bike-rental-backend
# Server Configuration
server.port=8080

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/ryder_rental
spring.datasource.username=postgres
spring.datasource.password=kasunay123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
jwt.secret=>mSYwInfBym1QA7KxoreSKFO8sZ3nsbiGZ5Gq8R6c8eJ
jwt.expiration=3600000

# CORS Configuration (for React frontend)
cors.allowed-origins=http://localhost:5173

# Logging
logging.level.org.springframework.security=DEBUG
logging.level.com.ryder=DEBUG

spring.security.enabled=false
